/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as DailyFocusRouteImport } from './routes/daily-focus'
import { Route as CustomTextRouteImport } from './routes/custom-text'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AiChatRouteImport } from './routes/ai-chat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ModuleModuleIdRouteImport } from './routes/module.$moduleId'
import { Route as MiniQuizUnUneRouteImport } from './routes/mini-quiz.un-une'
import { Route as LessonLessonIdRouteImport } from './routes/lesson.$lessonId'

const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyFocusRoute = DailyFocusRouteImport.update({
  id: '/daily-focus',
  path: '/daily-focus',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomTextRoute = CustomTextRouteImport.update({
  id: '/custom-text',
  path: '/custom-text',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AiChatRoute = AiChatRouteImport.update({
  id: '/ai-chat',
  path: '/ai-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModuleModuleIdRoute = ModuleModuleIdRouteImport.update({
  id: '/module/$moduleId',
  path: '/module/$moduleId',
  getParentRoute: () => rootRouteImport,
} as any)
const MiniQuizUnUneRoute = MiniQuizUnUneRouteImport.update({
  id: '/mini-quiz/un-une',
  path: '/mini-quiz/un-une',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonLessonIdRoute = LessonLessonIdRouteImport.update({
  id: '/lesson/$lessonId',
  path: '/lesson/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-chat': typeof AiChatRoute
  '/auth': typeof AuthRoute
  '/custom-text': typeof CustomTextRoute
  '/daily-focus': typeof DailyFocusRoute
  '/onboarding': typeof OnboardingRoute
  '/practice': typeof PracticeRoute
  '/progress': typeof ProgressRoute
  '/lesson/$lessonId': typeof LessonLessonIdRoute
  '/mini-quiz/un-une': typeof MiniQuizUnUneRoute
  '/module/$moduleId': typeof ModuleModuleIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-chat': typeof AiChatRoute
  '/auth': typeof AuthRoute
  '/custom-text': typeof CustomTextRoute
  '/daily-focus': typeof DailyFocusRoute
  '/onboarding': typeof OnboardingRoute
  '/practice': typeof PracticeRoute
  '/progress': typeof ProgressRoute
  '/lesson/$lessonId': typeof LessonLessonIdRoute
  '/mini-quiz/un-une': typeof MiniQuizUnUneRoute
  '/module/$moduleId': typeof ModuleModuleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-chat': typeof AiChatRoute
  '/auth': typeof AuthRoute
  '/custom-text': typeof CustomTextRoute
  '/daily-focus': typeof DailyFocusRoute
  '/onboarding': typeof OnboardingRoute
  '/practice': typeof PracticeRoute
  '/progress': typeof ProgressRoute
  '/lesson/$lessonId': typeof LessonLessonIdRoute
  '/mini-quiz/un-une': typeof MiniQuizUnUneRoute
  '/module/$moduleId': typeof ModuleModuleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-chat'
    | '/auth'
    | '/custom-text'
    | '/daily-focus'
    | '/onboarding'
    | '/practice'
    | '/progress'
    | '/lesson/$lessonId'
    | '/mini-quiz/un-une'
    | '/module/$moduleId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-chat'
    | '/auth'
    | '/custom-text'
    | '/daily-focus'
    | '/onboarding'
    | '/practice'
    | '/progress'
    | '/lesson/$lessonId'
    | '/mini-quiz/un-une'
    | '/module/$moduleId'
  id:
    | '__root__'
    | '/'
    | '/ai-chat'
    | '/auth'
    | '/custom-text'
    | '/daily-focus'
    | '/onboarding'
    | '/practice'
    | '/progress'
    | '/lesson/$lessonId'
    | '/mini-quiz/un-une'
    | '/module/$moduleId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiChatRoute: typeof AiChatRoute
  AuthRoute: typeof AuthRoute
  CustomTextRoute: typeof CustomTextRoute
  DailyFocusRoute: typeof DailyFocusRoute
  OnboardingRoute: typeof OnboardingRoute
  PracticeRoute: typeof PracticeRoute
  ProgressRoute: typeof ProgressRoute
  LessonLessonIdRoute: typeof LessonLessonIdRoute
  MiniQuizUnUneRoute: typeof MiniQuizUnUneRoute
  ModuleModuleIdRoute: typeof ModuleModuleIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily-focus': {
      id: '/daily-focus'
      path: '/daily-focus'
      fullPath: '/daily-focus'
      preLoaderRoute: typeof DailyFocusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-text': {
      id: '/custom-text'
      path: '/custom-text'
      fullPath: '/custom-text'
      preLoaderRoute: typeof CustomTextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-chat': {
      id: '/ai-chat'
      path: '/ai-chat'
      fullPath: '/ai-chat'
      preLoaderRoute: typeof AiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/module/$moduleId': {
      id: '/module/$moduleId'
      path: '/module/$moduleId'
      fullPath: '/module/$moduleId'
      preLoaderRoute: typeof ModuleModuleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mini-quiz/un-une': {
      id: '/mini-quiz/un-une'
      path: '/mini-quiz/un-une'
      fullPath: '/mini-quiz/un-une'
      preLoaderRoute: typeof MiniQuizUnUneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson/$lessonId': {
      id: '/lesson/$lessonId'
      path: '/lesson/$lessonId'
      fullPath: '/lesson/$lessonId'
      preLoaderRoute: typeof LessonLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiChatRoute: AiChatRoute,
  AuthRoute: AuthRoute,
  CustomTextRoute: CustomTextRoute,
  DailyFocusRoute: DailyFocusRoute,
  OnboardingRoute: OnboardingRoute,
  PracticeRoute: PracticeRoute,
  ProgressRoute: ProgressRoute,
  LessonLessonIdRoute: LessonLessonIdRoute,
  MiniQuizUnUneRoute: MiniQuizUnUneRoute,
  ModuleModuleIdRoute: ModuleModuleIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
